### ISSUE TITLE
Little bug list

### ISSUE THREAD

**Issue by pjfranzini** [aomran/curri#138]
-- modals do not work when account info accordion is open

-- when registering as a student, the blue asterisks for required field appear in the text boxes as well as on the text labels

**Comment by pjfranzini** [comment]
another cut-off issue: even when not on a small screen, cant scroll down to the bottom of date or hour selection of endtime:
![ss](https://f.cloud.github.com/assets/3428214/2299371/e030f34a-a0cb-11e3-80d3-3081c81b68cf.jpg)

**Comment by nachiketkumar** [comment]
Re bugs- 
- I thought that from a workflow point of view, the modal shouldn't show up at all when the account accordion is open. I see the modal show up- the semi transparent black background doesn't though. The reason is that when you have clicked the account button, it is presumably to log out or edit profile. I realize that you can click on other stuff on the screen and have it work though.
- I tried to invite a student to get the URL for student registration but I didn't see it show up in my logs. Is there another way I should be doing it?
- I dont see the date/time cutoff as you do-weird.
  ![screen shot 2014-03-01 at 9 17 23 am](https://f.cloud.github.com/assets/3782899/2301573/455b308e-a14c-11e3-97d6-49bef3ecab98.png)

**Comment by pjfranzini** [comment]
Re the student, yes there is a new way, I just wrote it up yesterday in the wiki after relearning how to do it. The reason there is a new way is because development emails now disappear "into thin air".

You could also invite a student in the live app, dashboard etc, from our demo account, using your own email for the invite so that you can read it.

Re the modal, I see the modal show up WITH the semitransparent black background -- everywhere (i.e. no hole-in-the-fog window). And I can't use the modal. Your argument makes sense, but considering one can forget and leave the accordion open...it looks buggy. Maybe eventually the accordion should snap back shut if one clicks anywhere else but on the links in the accordion. Hopefully it isn't much of a problem for users given they would tend to be on laptops (smaller screens, wouldnt tend to leave accordions open). Though a teacher might have a bigger screen at home...

**Comment by nachiketkumar** [comment]
totally stumped for the moment re. why new student forms are looking like that. I will have to spend some more time trying to figure it out.

**Comment by aomran** [comment]
The student form is probably very very low priority.
