### ISSUE TITLE
Simplify ratings

### ISSUE THREAD

**Issue by aomran** [aomran/curri#144]
I think our assumptions that:

a) students would rate multiple times per checkpoint
b) teachers wanted to see rating data over time

were wrong. People are simply too busy to do this. They want the least work with the most gains. The students usually have one good time where self-assessment is appropriate, and that's usually after they've done an exercise. Teachers on the other hand want the most feedback during a lesson not before or after. So they are looking for "realtime" + "up to date" information.

If this is the case then it might make sense to simplify the whole system. Collect only 1 rating per student per checkpoint and just update it. This replaces the current more complex system where every rating is a new "object".

**Comment by aomran** [comment]
This would take away the ability to do complex analytics but we haven't been able to come up with concrete, practical and useful ways of displaying the information. Even the simple "realtime" bars have suffered because they require a lot of energy from the teachers to make them work.

**Comment by nachiketkumar** [comment]
So basically the front end would not change? We are simplifying only our own backend, is that correct? Along with having removed phasing?

**Comment by aomran** [comment]
Yeah back end. If we change the front end it'll be for a different reason.

**Comment by Peak19** [comment]
It seems to me you're probably right here Ahmed. 

It's possible time is still relevant but maybe not in the way were thinking. What do you think about including a frequency graph indicating when students voted? This would be very useful when interpreting how much trust to put in the data you're getting. It would also be a subtle encourager to remind teachers to vote. We saw that people were voting up to 4 days later. I think a teacher should know this information. [I'll add this to Trello]

But, for the time being, what about just including pre-phase and real-time as the available options for now? 

I'm curious about what happens when if we drop content into Curri and students are interacting with it more. With only learning objectives I can see how students would be reticent to rate into the future - but with all the content provided? They might actually be able to offer an accurate opinion on their understanding. 

My suggestion is we leave the back-end as is right now. We have to also remember that the way Curri is used might change quite a bit if we get an eager teacher to pilot it.
