### ISSUE TITLE
Import and Export Data

### ISSUE THREAD

**Issue by aomran** [aomran/curri#89]
Exporting data (checkpoints and ratings) is an important data portability offering for both teachers and students. We need to allow users to export a classroom and get a bunch of CSV files. What they would get is a zip file with the classroom name. Inside the folder is folders for each track. Inside the track folders there is a CSV file that lists the checkpoints and another CSV file that list the ratings. Teachers get aggregate rating data while students only get their rating data. This is a big feature so it will have to wait for now.

Importing data is what we should focus on in the short term. Adding one checkpoint at a time will probably be tedious. We have two solutions:
1. Allow the user to add additional rows to the checkpoint form. So they click "Add another checkpoint" and two additional textboxes appear. This way they can add 1+ checkpoints per form submission.
2. Allow the user to import checkpoints from a CSV file. The first row needs to have the column headers: "Expectation" and "Success Criteria". Subsequent rows will have the actual checkpoint information.  If a row is missing this information then the upload will fail.

Which one should we go with? Why? Is there a reason to include both? Keep in mind that each solution comes with its own issues. For the CSV: do people know how to export this type of file?, can they get the headers right?, etc.

**Comment by nachiketkumar** [comment]
As for exporting, I think generating .csv files is fair game, and would be an acceptable solution. I can't imagine what other format we could export in that makes sense, but there might be a few more options.

For importing, the easier solution from a workflow for teachers would be an 'add another checkpoint' button and allow 1+ checkpoints per form.
- We don't rely on them formatting the imported .csv file correctly.
- We are unlikely to have power users at this stage. They would have to make a .csv file anyway in order to import it, so till we get pushback about a better way to import data, I would suggest we stick with 'add another checkpoint'. We could even enhance this by letting the user select a greater number of rows to add, from a dropdown. i.e 'Add X (1-10) more checkpoints'

**Comment by pjfranzini** [comment]
Ok that makes sense, although I think a csv import option could be useful eventually. This would be a good point to get feedback on from our pilot/beta teachers -- poll them on how they would like to be able to input their info.

**Comment by Peak19** [comment]
I've added a question to our HackerYou Pilot document regarding teacher preference for checkpoint input. Personally, I would prefer to add my checkpoints using a CSV - but I might just be weird like that.

**Comment by pjfranzini** [comment]
You might want to merge that up with my "How would you like to be able to enter data?" question which was supposed to address the same issue. Also please feel free to move around these ideas I added at the end as rough notes not to forget them.
